### ISSUE TITLE
Making a non-template VM doesn't prompt for an SSH key

### ISSUE THREAD

**Issue by crigney3** [com6056/proxstar#9]
If you try to create a new VM without using the CentOS or Ubuntu template, the page doesn't have an option to add an ssh key. It then won't let you create the VM due to not having an ssh key.

**Comment by com6056** [comment]
The option to use an SSH key is only available when using a template, I did mess up when checking the SSH key though. It should only check when using a template, which should be fixed here: https://github.com/com6056/proxstar/commit/de4e4644a007cc2fb1d2e011fe5806e74beeff40
Thanks!
